name: Build MacOS

on: 
  push:

  # Manual run
  workflow_dispatch:

jobs:
  build_macos_x86_64:
    runs-on: macos-10.15
    defaults:
      run:
        working-directory: ./python3-macos    
    strategy:
      matrix:
        env:
          - { PYVER: 3.7.15 }
          
          - { PYVER: 3.8.15 }
          
          - { PYVER: 3.9.15 }

          - { PYVER: 3.10.8 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4'
    - name: Build Python
      run: |
        # Make the script runnable
        chmod +x build.sh

        # Set env parameters
        export ARCH=x86_64
        export PYVER=${{ matrix.env.PYVER }}

        # Run the build script
        ./build.sh
    - name: Create package
      id: create_package
      run: |
        cd x86_64/embedabble           
        package_filename=python3-macos-${{ matrix.env.PYVER }}-x86_64.zip
        7z a -tzip $package_filename * -r
        echo ::set-output name=package_filename::$package_filename
    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        path: python3-macos/x86_64/embedabble/python3-macos-${{ matrix.env.PYVER }}-x86_64.zip
        if-no-files-found: error

  build_macos_universal2:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./python3-macos    
    strategy:
      matrix:
        env:          
          - { PYVER: 3.8.13 }
          
          - { PYVER: 3.9.12 }

          - { PYVER: 3.10.4 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build Python
      run: |
        # Make the script runnable
        chmod +x build.sh

        # Set env parameters
        export ARCH=universal2
        export PYVER=${{ matrix.env.PYVER }}

        # Run the build script
        ./build.sh
    - name: Create package
      id: create_package
      run: |
        cd universal2/embedabble           
        package_filename=python3-macos-${{ matrix.env.PYVER }}-universal2.zip
        7z a -tzip $package_filename * -r
        echo ::set-output name=package_filename::$package_filename
    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        path: python3-macos/universal2/embedabble/${{ steps.create_package.outputs.package_filename }}
        if-no-files-found: error